name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      # Set up Prerequisites
      - name: âš™ï¸ Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: ğŸ§ƒ Install just
        uses: extractions/setup-just@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Install required tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - name: ğŸ“¦ Install Node.js dependencies
        run: npm ci

      # Fix rust code
      - run: cargo clippy --fix --workspace
      - run: cargo fmt --all

      # run pre-commit hooks
      - run: pip install pre-commit
      - run: pre-commit install
      - run: pre-commit run --all-files

      # run autofix-ci action
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
